### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by domatop** [adujardin/zed-openpose#4]
Thanks for offering your wonderful code.

I have a trouble building with the source
the error messages are below here and the problem seems to be related to opencv (But I already build opencv latest version)

could you help me please?

---------------------------------------------------------------------------------------------------------------------------------------
$ make

Scanning dependencies of target zed_openpose
[ 33%] Building CXX object CMakeFiles/zed_openpose.dir/src/GLViewer.o
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:12:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:23:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:31:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:39:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:50:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}\n";
         ^
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:58:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}\n";
         ^
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:85:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^
/home/vdo-gt/tmp/zed-openpose/src/GLViewer.cpp:93:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^
[ 66%] Building CXX object CMakeFiles/zed_openpose.dir/src/main.o
In file included from /usr/local/include/openpose/filestream/headers.hpp:9:0,
                 from /usr/local/include/openpose/headers.hpp:17,
                 from /home/vdo-gt/tmp/zed-openpose/include/utils.hpp:17,
                 from /home/vdo-gt/tmp/zed-openpose/src/main.cpp:16:
/usr/local/include/openpose/filestream/fileStream.hpp:54:32: error: ‘CV_IMWRITE_JPEG_QUALITY’ was not declared in this scope
                             = {CV_IMWRITE_JPEG_QUALITY, 100, CV_IMWRITE_PNG_COMPRESSION, 9});
                                ^
/usr/local/include/openpose/filestream/fileStream.hpp:54:62: error: ‘CV_IMWRITE_PNG_COMPRESSION’ was not declared in this scope
                             = {CV_IMWRITE_JPEG_QUALITY, 100, CV_IMWRITE_PNG_COMPRESSION, 9});
                                                              ^
/usr/local/include/openpose/filestream/fileStream.hpp:54:92: error: could not convert ‘{<expression error>, 100, <expression error>, 9}’ from ‘<brace-enclosed initializer list>’ to ‘const std::vector<int>&’
                             = {CV_IMWRITE_JPEG_QUALITY, 100, CV_IMWRITE_PNG_COMPRESSION, 9});
                                                                                            ^
/usr/local/include/openpose/filestream/fileStream.hpp:56:87: error: ‘CV_LOAD_IMAGE_ANYDEPTH’ was not declared in this scope
     OP_API cv::Mat loadImage(const std::string& fullFilePath, const int openCvFlags = CV_LOAD_IMAGE_ANYDEPTH);
                                                                                       ^
In file included from /usr/local/include/openpose/producer/headers.hpp:5:0,
                 from /usr/local/include/openpose/headers.hpp:32,
                 from /home/vdo-gt/tmp/zed-openpose/include/utils.hpp:17,
                 from /home/vdo-gt/tmp/zed-openpose/src/main.cpp:16:
/usr/local/include/openpose/producer/datumProducer.hpp: In constructor ‘op::DatumProducer<TDatumsNoPtr>::DatumProducer(const std::shared_ptr<op::Producer>&, long long unsigned int, long long unsigned int, const std::shared_ptr<std::pair<std::atomic<bool>, std::atomic<int> > >&)’:
/usr/local/include/openpose/producer/datumProducer.hpp:63:33: error: ‘CV_CAP_PROP_POS_FRAMES’ was not declared in this scope
                 spProducer->set(CV_CAP_PROP_POS_FRAMES, (double)frameFirst);
                                 ^
/usr/local/include/openpose/producer/datumProducer.hpp: In member function ‘std::pair<bool, std::shared_ptr<_Tp1> > op::DatumProducer<TDatumsNoPtr>::checkIfRunningAndGetDatum()’:
/usr/local/include/openpose/producer/datumProducer.hpp:95:41: error: ‘CV_CAP_PROP_POS_FRAMES’ was not declared in this scope
                         spProducer->set(CV_CAP_PROP_POS_FRAMES, spProducer->get(CV_CAP_PROP_POS_FRAMES) + increment);
                                         ^
/usr/local/include/openpose/producer/datumProducer.hpp:100:82: error: ‘CV_CAP_PROP_POS_FRAMES’ was not declared in this scope
                 const auto nextFrameNumber = (unsigned long long)spProducer->get(CV_CAP_PROP_POS_FRAMES);
                                                                                  ^
/usr/local/include/openpose/producer/datumProducer.hpp:130:80: error: ‘CV_GRAY2BGR’ was not declared in this scope
                             cv::cvtColor(datum.cvInputData, datum.cvInputData, CV_GRAY2BGR);
                                                                                ^
In file included from /usr/local/include/openpose/wrapper/headers.hpp:5:0,
                 from /usr/local/include/openpose/headers.hpp:44,
                 from /home/vdo-gt/tmp/zed-openpose/include/utils.hpp:17,
                 from /home/vdo-gt/tmp/zed-openpose/src/main.cpp:16:
/usr/local/include/openpose/wrapper/wrapper.hpp: In member function ‘void op::Wrapper<TDatums, TDatumsSP, TWorker, TQueue>::configure(const op::WrapperStructPose&, const op::WrapperStructFace&, const op::WrapperStructHand&, const op::WrapperStructExtra&, const op::WrapperStructInput&, const op::WrapperStructOutput&)’:
/usr/local/include/openpose/wrapper/wrapper.hpp:526:90: error: ‘CV_CAP_PROP_FRAME_WIDTH’ was not declared in this scope
                 producerSize = Point<int>{(int)wrapperStructInput.producerSharedPtr->get(CV_CAP_PROP_FRAME_WIDTH),
                                                                                          ^
/usr/local/include/openpose/wrapper/wrapper.hpp:527:90: error: ‘CV_CAP_PROP_FRAME_HEIGHT’ was not declared in this scope
                                           (int)wrapperStructInput.producerSharedPtr->get(CV_CAP_PROP_FRAME_HEIGHT)};
                                                                                          ^
/usr/local/include/openpose/wrapper/wrapper.hpp:951:88: error: ‘CV_CAP_PROP_FPS’ was not declared in this scope
                                         0. : wrapperStructInput.producerSharedPtr->get(CV_CAP_PROP_FPS));
                                                                                        ^
/usr/local/include/openpose/wrapper/wrapper.hpp:965:78: error: there are no arguments to ‘CV_FOURCC’ that depend on a template parameter, so a declaration of ‘CV_FOURCC’ must be available [-fpermissive]
                     wrapperStructOutput.writeVideo, CV_FOURCC('M','J','P','G'), originalVideoFps, finalOutputSize
                                                                              ^
/usr/local/include/openpose/wrapper/wrapper.hpp:965:78: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/vdo-gt/tmp/zed-openpose/src/main.cpp: In function ‘void run()’:
/home/vdo-gt/tmp/zed-openpose/src/main.cpp:447:58: error: ‘CV_RGBA2RGB’ is not a member of ‘cv’
                 cv::cvtColor(inputImageRGBA, inputImage, cv::CV_RGBA2RGB);
                                                          ^
CMakeFiles/zed_openpose.dir/build.make:86: 'CMakeFiles/zed_openpose.dir/src/main.o' 타겟에 대한 명령이 실패했습니다
make[2]: *** [CMakeFiles/zed_openpose.dir/src/main.o] 오류 1
CMakeFiles/Makefile2:67: 'CMakeFiles/zed_openpose.dir/all' 타겟에 대한 명령이 실패했습니다
make[1]: *** [CMakeFiles/zed_openpose.dir/all] 오류 2
Makefile:83: 'all' 타겟에 대한 명령이 실패했습니다
make: *** [all] 오류 2

**Comment by mrbjkk** [comment]
@domatop I met the same issue when compiling. Have you found any solution? Thank you.

**Comment by adujardin** [comment]
It seems to be related to the old OpenCV C API, that was removed in OpenCV 4.
You should try to use OpenCV 3 instead for now.

**Comment by mrbjkk** [comment]
@adujardin Thanks for the reply. I am using OpenCV 3.4.6 and some other issues happened
The error message is:
Scanning dependencies of target zed_openpose
[ 33%] Building CXX object CMakeFiles/zed_openpose.dir/src/main.o
[ 66%] Building CXX object CMakeFiles/zed_openpose.dir/src/GLViewer.o
/home/yurik/software/zed-openpose/src/GLViewer.cpp:12:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:23:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:31:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:39:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:50:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}\n";
         ^~~~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:58:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}\n";
         ^~~~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:85:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:93:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp: In member function ‘void GLViewer::initialize()’:
/home/yurik/software/zed-openpose/src/GLViewer.cpp:627:15: error: invalid conversion from ‘char’ to ‘char*’ [-fpermissive]
     argv[0] = '\0';
               ^~~~
CMakeFiles/zed_openpose.dir/build.make:62: recipe for target 'CMakeFiles/zed_openpose.dir/src/GLViewer.o' failed
make[2]: *** [CMakeFiles/zed_openpose.dir/src/GLViewer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/zed_openpose.dir/all' failed
make[1]: *** [CMakeFiles/zed_openpose.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by adujardin** [comment]
Could you try replacing this 2 lines:

https://github.com/adujardin/zed-openpose/blob/d0f08b1c6a3adf060a34ed06fd849a0c0512eef7/src/GLViewer.cpp#L626-L627

by:

```c++
char *argv[1] = {(char*)"openpose"};
```

Or simply compile with `-fpermissive` option in the cmake here https://github.com/adujardin/zed-openpose/blob/d0f08b1c6a3adf060a34ed06fd849a0c0512eef7/CMakeLists.txt#L37

**Comment by mrbjkk** [comment]
@adujardin I tried both the approaches and get the same error:

Scanning dependencies of target zed_openpose
[ 33%] Building CXX object CMakeFiles/zed_openpose.dir/src/GLViewer.o
[ 66%] Building CXX object CMakeFiles/zed_openpose.dir/src/main.o
/home/yurik/software/zed-openpose/src/GLViewer.cpp:12:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:23:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:31:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:39:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:50:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}\n";
         ^~~~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:58:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}\n";
         ^~~~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:85:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
/home/yurik/software/zed-openpose/src/GLViewer.cpp:93:9: warning: ISO C++ forbids converting a string constant to ‘GLchar* {aka char*}’ [-Wwrite-strings]
         "}";
         ^~~
[100%] Linking CXX executable zed_openpose
/usr/bin/ld: cannot find -lopencv_calib3d
/usr/bin/ld: cannot find -lopencv_core
/usr/bin/ld: cannot find -lopencv_dnn
/usr/bin/ld: cannot find -lopencv_features2d
/usr/bin/ld: cannot find -lopencv_flann
/usr/bin/ld: cannot find -lopencv_highgui
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: cannot find -lopencv_imgproc
/usr/bin/ld: cannot find -lopencv_ml
/usr/bin/ld: cannot find -lopencv_objdetect
/usr/bin/ld: cannot find -lopencv_photo
/usr/bin/ld: cannot find -lopencv_shape
/usr/bin/ld: cannot find -lopencv_stitching
/usr/bin/ld: cannot find -lopencv_superres
/usr/bin/ld: cannot find -lopencv_video
/usr/bin/ld: cannot find -lopencv_videoio
/usr/bin/ld: cannot find -lopencv_videostab
collect2: error: ld returned 1 exit status
CMakeFiles/zed_openpose.dir/build.make:131: recipe for target 'zed_openpose' failed
make[2]: *** [zed_openpose] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/zed_openpose.dir/all' failed
make[1]: *** [CMakeFiles/zed_openpose.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Is it due to a wrong configuration for my opencv? 
By the way, I am using Ubuntu 18.04

**Comment by adujardin** [comment]
That's not the same error (you can ignore the warnings), the program now compiles but failed to link to opencv (`cannot find -l...`).
Make sure OpenCV is correctly installed and that the cmake is able to find it.
You can remove the build folder and start again, to remove the cmake cache and see if it helps.

**Comment by mrbjkk** [comment]
@adujardin I specified the OpenCV directory in CMakeLists.txt and it works fine.
Now I attempt to modify the ZED initial parameters in source files to fit my machine.
Thanks for your great contribution.
