### ISSUE TITLE
Save the 3D points of the skeleton independently

### ISSUE THREAD

**Issue by Lemany** [adujardin/zed-openpose#5]
Good evening everyone,

First of all, I thank Aymeric Dujardin for this great code that is both easy to understand and to handle.

I tried to find a solution to my problem which is to be able to save in excel file or in another type, the points 3D corresponding to model "BODY 25".

With some research, I came across this readme:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format
and a test code where it is saved in JSON format, unfortunately it saves for each image a JSON file. It's not efficient and my performance decrease.

My goal is to fill an excel file permanently, having the labels with their coordinates at each frame.

I hope you could help me .

Thank you so much !

**Comment by Adhithiyan03** [comment]
Hi did u find the solution
