### ISSUE TITLE
Building error in Visual Studio 2017, with openpose update Oct. 2019

### ISSUE THREAD

**Issue by ianni67** [adujardin/zed-openpose#9]
I'm experiencing a weird compilation error while building zed-openflow under WIndows 10 with Visual Studio 2017. 
```
Error	C2664	'op::Point<int> op::flagsToPoint(const op::String &,const op::String &)': cannot convert argument 1 from 'fLS::clstring' to 'const op::String &'	
zed_openpose	C:\Users\ianni\Desktop\SW\zed-openpose\src\main.cpp	173	
```
I'm confused. Looks like this error is somewhat related to some recent changes in the OpenPose code, made on Oct. 2019 but cannot confirm that. I tried re-installing, re-compiling, explicitely casting, to no avail. The error repeates for each FLAG that is converted with flagsToPoint.

Please, help or advice. I'm stuck.

**Comment by adujardin** [comment]
Indeed, they seem to have changed the API, I have the same issue now. You can fix this by casting each FLAG like this :
```cpp
op::flagsToPoint(std::string(FLAGS_output_resolution).c_str(), "-1x-1");
```

There are also similar issues with cv::Mat, for instance, this line : 
https://github.com/adujardin/zed-openpose/blob/084ad3170eb1ebe0d6cb71e6524b4aabe4336429/src/main.cpp#L510 
needs to be changed to :
```cpp
outputImage = *((cv::Mat*)opOutputToCvMat.formatToCvMat(outputArray2).getCvMat());
```

I'll try to push an update soon.

**Comment by ianni67** [comment]
I can confirm that the fix for flags works also for me. 
I'll check for the others - and wait for your update, anyway.
Thank you very much for your help, and for sharing your great work.

**Comment by ianni67** [comment]
Hello, did you find the time to fix the issue?
Thank you very much for the help

**Comment by adujardin** [comment]
The latest commit 59f9cde should fix your issue. I didn't test it thoroughly but it compiled and launched fine with the current version of Openpose.

**Comment by ianni67** [comment]
Sorry for the very late feedback. My project was in standby for a while, but now I'm back working on it. 
_The issue is gone now, and everything works ok_ - albeit, I had to revert from CUDA 10.2 to CUDA 10.0 because openpose does not work with 10.2 (at least, this is my case and the case of several other developers).
Thank you very much for your effort.
